version: '3'

services:
  s3fs:
    image: docker-s3fs:alpine
    cap_add:
      - MKNOD
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    volumes:
      - "./bucket:/mnt/bucket"
    command: s3fs -f -o allow_other -o passwd_file=/etc/passwd-s3 -o use_cache=/tmp ${S3_BUCKET_NAME} /mnt/bucket
